ASI.Basecode.WebApp/Controllers/NavosController.cs
using Microsoft.AspNetCore.Mvc;

namespace ASI.Basecode.WebApp.Controllers
{
    public class NavosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ASI.Basecode.WebApp/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<header class="@((ViewBag.LoginView == true) ? "hide-navbar" : "")">
    <div class="logosec hover-pointer">
        <img src="~/img/asi-logo-invert.svg"
             style="width: 185px;" alt="logo"
             onclick="window.location.href = '@Url.Action("Index", "Home")';">
    </div>
    <a asp-action="Index" asp-controller="Navos">Navos</a>
    <div class="logosec">
        @HttpContextAccessor.HttpContext.Session.GetString("UserName")
        <div class="mr-20 hover-pointer" style="position: relative">
            <div class="dp">
                <img src="~/img/profile-logo.png"
                     class="dpicn hover-pointer"
                     alt="dp">
            </div>
            <div class="dropdown">
                <ul>
                    <li>
                        <i class="fa-solid fa-gear"></i>
                        <a href="#">Settings</a>
                    </li>
                    <li>
                        <i class="fa-solid fa-right-from-bracket"></i>
                        <a asp-action="SignOutUser" asp-controller="Account">Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

ASI.Basecode.WebApp/Views/Shared/_Layout.cshtml
@using static ASI.Basecode.Resources.Views.Screen

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/main.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/purecss@3.0.0/build/pure-min.css" integrity="sha384-X38yfunGUhNzHpBaEBsWLO+A0HDYOQi8ufWDkZ0k9e0eXz/tH3II7uKZ9msv++Ls" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    @RenderSection("Styles", required: false)
</head>
<body>
    @Html.Partial("_Header")
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>
   @*  <footer class="border-top footer text-muted">
        <div class="container">
            @Copyright
        </div>
    </footer> *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>
    <script src="https://kit.fontawesome.com/7a7c645416.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        // Configure Toastr options
        toastr.options = {
            positionClass: "toast-top-center", // Set the notification position to center
            timeOut: 3000,
            closeButton: true,
            progressBar: true
        };

    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>